version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-world-app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
